---
title: "Home"
title-block-banner: "#004152"
listing:
  contents: posts
  sort: "date desc"
  max-items: 3
  type: grid
---

## Welcome

I work at the intersection of digital scholarship, cultural heritage and ocean sustainability, helping people connect with research, collections and knowledge through digital tools, communication and public engagement.

I currently work in [Digital Scholarship](https://library.soton.ac.uk/digital-scholarship) at the University of Southampton, and manage digital engagement for the [Ocean Decade Heritage Network](https://www.oceandecadeheritage.org/), supporting efforts to better integrate ocean heritage into the [UN Ocean Decade](https://oceandecade.org/).

Alongside this, I offer freelance consultancy in digital engagement, website management, science communication and heritage-focused projects.

[About me](about-me.qmd){.btn .btn-primary .cta-btn}

<br>

## Services

* Freelance consultancy on digital engagement and science communication
* Social media strategy, content creation, and management
* Website updates, design support, and accessibility recommendations
* Science communication and public engagement content

[Get in touch](https://ek-ku.github.io/blog/blog.html){.btn .btn-primary .cta-btn}

<br>

## Latest Blog Posts

On my [blog](https://ek-ku.github.io/blog/blog.html), I write about digital tools, research communication, and the intersections between culture, science, and the sea.

Check out my latest blog posts: